Fix setup.cfg Get and Update QuotaClass
In setup.cfg GetQuotaClass and UpdateQuotaClass are not in
zunclient.osc.v1.quotas but in zunclient.osc.v1.quota_classes.

Due to this mistake openstack complete throws the exception
ImportError: module 'zunclient.osc.v1.quotas' has no attribute
'GetQuotaClass'

Change-Id: I201e15b3590598b910731e4afdc3776b870aa282