Handle various permutation of query params
This is an attempt to fix the intermittent error on py35 gate.
By analyzing the logs, it seems the test test_containers_resize
failed on either

  KeyError: '/v1/containers/1234/resize?w=121&h=56'

Or

  KeyError: '/v1/containers/1234/resize?h=56&w=121'

It looks there are two permutation of the query string that causes
the failure. This commit tried to fix it.

Change-Id: Ie068af5828ad852530aab659ec6891600d5f5e9f
Closes-Bug: #1665460